SCREEN_WIDTH = 1300
SCREEN_HEIGHT = 700
FPS = 75

GRAVITY = 2

LEFT = 'K_LEFT'
RIGHT = 'K_RIGHT'
UP = 'K_UP'
DOWN = 'K_DOWN'

BACKGROUND_ANIMATION_SPEED = 12

VIKING_JUMPING_HEIGHT = 40
VIKING_Y_VELOCITY = VIKING_JUMPING_HEIGHT
VIKING_X_VELOCITY = 14

VIKING_WALKING_ANIMATION_SPEED = 4
VIKING_JUMPING_ANIMATION_SPEED = 100
VIKING_DISTANCE = 100

FLOOR_HEIGHT = 40